### ISSUE TITLE
Shadow settings not saving with AWD

### ISSUE THREAD

**Issue by jonarnold** [awaytools/AwayBuilder#170] opened 2013-06-12 03:04 UTC
I can configure shadows in v 0.9.5 and they look great, but shadow settings don't seem to be saving. When I save, close, and reopen, the shadows are gone as are the shadow settings.

**Comment by 80prozent** [comment] 2013-06-16 11:50
Hi 
I cannot reproduce this issue, but it was also reported on the forum, so there might have been a binary of AwayBuilder, that didnt saved/imported shadows correctly. 
Since its working for me (with the current download-version), and i did no fix for this, i suspect this was a bug in AwayBuilder and not in AWD. 

I close this issue, but if anyone can reproduce, please open it again.

**Closed as completed by 80prozent** 2013-06-16 11:50 UTC
