### ISSUE TITLE
level.awd throws error when loaded back into interface after it has been saved and then saved again

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#105] opened 2013-05-06 08:31 UTC
**Steps to reproduce**
- open level.awd
- save as level_saved.awd
- open level_saved.awd
- save as level_saved2.awd

**Comment by 80prozent** [comment] 2013-05-06 10:42
I believe this is the same issue as with the sponza.awd. i am not home, so i cannot test, but i believe this is caused by not correct imported ColorMaterials too. When exporting the file, all materials that has no diffuse or ambient textures are saved as ColorMaterials, and when importing them back, the shadingMethods of the MaterialVO are not set...

**Comment by 80prozent** [comment] 2013-05-06 19:11
Fixed in _fillMaterial()  - SmartFactoryModelBase.as

**Closed as completed by 80prozent** 2013-05-06 19:11 UTC
Labels: bug
