### ISSUE TITLE
Full featured .awd file needed

### ISSUE THREAD

**Issue by pirrest** [awaytools/AwayBuilder#1] opened 2013-02-25 17:44 UTC
Hello, Richard,
To continue development we need another .awd file with all types of items in it, to test tree UI component, its parsing etc.
Right now some of the assets are embeded inside app itself to show bear file,
but we need to remove them, and to do that we need to have them inside .awd (or defined by external links in it)
Also we need an example of parsing that file, to see all possible options..

Could you please provide a file and parsing example? Thanks

**Comment by richardolsson** [comment] 2013-02-26 06:42
You can download a file with geometries, meshes, embedded textures and materials here:
https://www.dropbox.com/s/imhvzc2zdsb61pb/level.awd.zip

I don't have a loading sample though, and am not scheduled to work on this project until next week, but have you not loaded files using the Away3D loading system before? Just load using AssetLoader or AssetLibrary (if you're not already implementing your own library system) and listen for ASSET_COMPLETE events to get a reference to each asset found in the file(s).

**Comment by pirrest** [comment] 2013-02-26 08:20
Thank you, Richard. Assigning this on Mike, so he will use mentioned .awd file.

**Comment by keyemkey** [comment] 2013-02-26 15:09
Problem with loading this AWD.

Error: Invalid bitmapData: Width and height must be power of 2 and cannot exceed 2048

**Comment by pirrest** [comment] 2013-02-26 15:30
Richard, please take a look at what is wrong with AWD file.

**Comment by richardolsson** [comment] 2013-02-26 15:37
There is nothing wrong with the AWD file. AWD supports textures that are non-square and whose dimensions are not powers of two. However, such textures can't be rendered in Away3D. So you have to convert them as they come in.

Either override the ImageParser (or hack it), or just change the bitmap of every texture that comes in.

This is not a bug. It's by design. And AwayBuilder will need to be able to handle cases like this.

**Comment by Greg209** [comment] 2013-03-01 16:29
I'm gonna take a look at the Away3D parser to handle non-power of 2 image sizes so I've assigned this issue to me.

**Closed as completed** 2013-04-16 20:48 UTC
