### ISSUE TITLE
DAE skeleton animation errors #1034 and #3647

### ISSUE THREAD

**Issue by alkabano** [awaytools/AwayBuilder#218] opened 2013-07-11 17:02 UTC
Steps to reproduce:
1. Open AwayBuilder 1.0.0 Gold
2. Import robot-c90.dae from [archive](https://gist.github.com/alkabano/5ea3aa4be848d80ad857#file-robot-c90-7z) (based on model [c90 by AwesomeStudios](http://www.blendswap.com/blends/view/51961))

-- error 1034 way
3. Animations - SkeletonAnimationSet null - Animators - add SkeletonAnimator1
4. Scene Objects - Scene, c90 - Animator - select SkeletonAnimator1
5. Save to awd, reopen AwayBuilder, open awd

-- error 3647 way
3. Save to awd, reopen AwayBuilder, open awd
4. Animations - SkeletonAnimationSet null - Animators - add SkeletonAnimator1
5. Scene Objects - Scene, c90 - Animator - select SkeletonAnimator1

**Comment by 80prozent** [comment] 2013-07-11 17:46
Hi alkabano 

i think i found the cause for this:
After importing the collade file
- go into the the property panel of the Geometry.
- go into the panel for one of the SubGeometries 
- there you can see the SubGeometry is of Type = CompactSubGeometry 
- the type of a Subgeometry used for SkeletonAnimation should be Type = SkinnedSubGeometry
- i dont know why its imported as a wrong type (i will investigate)

quick fix for this:
- change the ScaleU or the ScaleV of the Geometry (and than set it back to 1 again)
- after changing the scaleU, the Subgeometry will be interpreted as Type = SkinnedSubGeometry, and exporting as AWD seams to work fine.

**Comment by 80prozent** [comment] 2013-07-11 20:01
This happens, because the DAEParser dispatches the Geometry-Event after the Geometry is created, and 
AwayBuilder adds this Geometry to the AwayBuilder-AssetLibrary. 
However, if the geometry is animated, the ColladaParser will switch the Subgeometries of the allready finalized Geometry into SkinnedSubGeometries (but AwayBuilder has allready created the Geometry in its AssetLibrary, and does not now it must update)

**Closed as completed** 2013-07-11 20:04 UTC
Labels: bug
