### ISSUE TITLE
On loading the polarbear once and loading it a second time, the root container name changes

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#75] opened 2013-05-02 23:52 UTC
**Steps to reproduce**
- Open polarbear.awd
- root container is called "containe0r.1"
- Open polarbear.awd again
- root container is now called "container0.2"

I suspect the name conflict resolver is getting a bit carried away in the assetlibrary

**Comment by 80prozent** [comment] 2013-05-05 03:10
This is caused by the AssetLibrary.conflictStrategy (APPEND_NUM_SUFFIX is default) and the fact that a Object deleted in the Library-panel is not deleted from the Assets.

If we do not take care in AwayBuilder, that every Asset has a unique name, the AssetLibrary.conflictStrategy might change the names of Assets on import. 
Since the names are used to access the assets (without AwayBuilder) this is not good.

A simple fix for this, would be, to set the AssetLibrary.conflictStrategy to IGNORE as default. This way Assetnames will only be changed if the User has asked for it.

**Comment by 80prozent** [comment] 2013-05-05 20:33
Changed the Default for AssetLibrary.conflictStrategy to IGNORE (in Away3d).

**Closed as completed by 80prozent** 2013-05-05 20:33 UTC
Labels: bug
